version: "3.3"
services:

  redis:
    image: "redis:latest"
    container_name: "${APP_NAME}-redis"
    command: ["redis-server","--port ${REDIS_PORT}", "--appendonly", "yes"]
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - ./assets/docker/redis/data:/data